export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';

export const DELETE_TRANSACTIONS_REQUEST = 'DELETE_TRANSACTIONS_REQUEST';
export const DELETE_TRANSACTIONS_SUCCESS = 'DELETE_TRANSACTIONS_SUCCESS';
export const DELETE_TRANSACTIONS_ERROR = 'DELETE_TRANSACTIONS_ERROR';
